spring:
  application:
    name: custom_context_holder
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: reports
    password: root123
    url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8081
